# Python base image
FROM python:3.9-slim

# LibreOffice install
RUN apt-get update && apt-get install -y libreoffice fonts-dejavu && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Working directory
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt requirements.txt

# Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose port
EXPOSE 5000

# Run Flask
CMD ["python", "app.py"]
